공통 컴포넌트(컬러선택창, 버튼, 페이지네이션 버튼, 프로필) 구현
Codeit-Part3-Taskify/Taskify pull request #17
Opened 2024-03-13 09:42 UTC by Jnnsu

[PR 규칙](https://www.notion.so/PR-rules-e68d631e586948478a5fa8408a464b92)

### 리뷰어에게

공통 컴포넌트 구현하였습니다.
- 프로필 컴포넌트
- 컬러 선택기
- 버튼 레이아웃과 페이지네이션 버튼

### 주요 변경사항

- 공통 컴포넌트 구현

### 스크린샷
![](https://ifh.cc/g/WNcLHc.png)
![](https://ifh.cc/g/7x8Jtk.png)

### 이슈

> close할 이슈 또는 관련 이슈

- closed: #11 
- related: #10

2024-03-13 09:52 UTC, yulmai999 reviewed
고생하셨습니다.
이미지파일같은경우 파비콘같은 컴파일이 필요하지않은 이미지는 public에 넣어도되지만 
컴포넌트내부에서 사용하는 이미지파일은
src/assets/images 폴더가 맞는위치인거같습니다

2024-03-13 12:28 UTC, haeyong9701 requested changes

2024-03-13 12:28 UTC, haeyong9701 commented on tsconfig.json
> +      "@/*": ["src/*"]
경로를 절대경로로 잘 바꿔주신 것 같습니다 👍

2024-03-13 16:37 UTC, Jnnsu commented
@yulmai999 
> 이미지파일같은경우 파비콘같은 컴파일이 필요하지않은 이미지는 public에 넣어도되지만
컴포넌트내부에서 사용하는 이미지파일은
src/assets/images 폴더가 맞는위치인거같습니다

해당 부분은 수정하는 것이 맞다고 생각되어 이미지 파일 위치를 변경해주었습니다. [https://github.com/Codeit-Part3-Taskify/Taskify/pull/17/commits/b9439500b085e5f4f05f16cc01cfd1deb556cfd4](https://github.com/Codeit-Part3-Taskify/Taskify/pull/17/commits/b9439500b085e5f4f05f16cc01cfd1deb556cfd4)

추가로 이미지 파일을 변경 후 절대경로를 통해 불러오면 오류가 납니다. 
eslint-import-resolver-typescript 플러그인을 설치해야 오류가 안날 듯 합니다.

2024-03-13 19:09 UTC, yulmai999 approved these changes

2024-03-13 23:47 UTC, haeyong9701 approved these changes

2024-03-14 03:26 UTC, Jnnsu commented
변경사항

1. 린트 관련 플러그인이 누락되어 있어 추가하였습니다.
- @typescript-eslint/eslint-plugin
- @typescript-eslint/parser

2. 불필요한 컴포넌트는 삭제하고, 나머지 컴포넌트는 Layout 폴더 바깥으로 이동하였습니다.

3. src 내의 이미지를 절대 경로로 불러오면 에러가 나서 상대 경로로 바꿔주었습니다.

2024-03-14 06:33 UTC, merged